name: Integration tests
on:
  push:
    branches:
    - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - 'main'
    paths:
    - 'vuejs/**'
    - '.github/workflows/vuejs-ci.yaml'

env:
    GOLANG_VERSION: '1.20'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  prepare-template:
    name: Prepare Cookiecutter Template
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Cookiecutter
      run: pip install cookiecutter
    - name: Run Cookiecutter
      run: cookiecutter --no-input -o $(pwd)/.data/ $(pwd)/vuejs/
    - name: Temporarily save cookiecutter output
      uses: actions/upload-artifact@v2
      with:
        name: vuejs-src
        path: .data/MyVueJSApp
        retention-days: 1

  test-image-functionality:
    name: Test Image
    runs-on: ubuntu-22.04
    needs: prepare-template
    steps:
    - name: Retrieve saved cookiecutter output
      uses: actions/download-artifact@v2
      with:
        name: vuejs-src
        path: .data/MyVueJSApp
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .data/MyVueJSApp
        load: true
        tags: app:test
    - name: Test container structure
      uses: plexsystems/container-structure-test-action@cc689017bbb16a3c98e6e87b0e07f92ad35a9df1
      with:
        image: app:test
        config: .data/MyVueJSApp/container-structure-test.yaml
    - name: Run integration test
      working-directory: .data/MyVueJSApp
      run: |
        docker run -p 8080:8080 app:test &
        sleep 1
        response=$(curl --connect-timeout 10 http://0.0.0.0:8080)
        if [[ $response != *"<title>MyVueJSApp</title>"* ]]; then
            exit 1
        fi

